name: Build
on:
  pull_request:
  push:
    tags:
      - v*.*.*
  release:
    types: [ created, published ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4

    - run: npm ci
    - run: npm run build
    - run: npm test
